version: '3.8'

services:
  mongodb:
    image: mongo
    # container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # backend:
  #   build: 
  #     context: ./backend
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/user
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - mongo
  backend:
    build : ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user
    depends_on:
      - mongodb

  # frontend:
  #   build: 
  #     context: ./frontend
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data: {}
